name: german_tv_m3u
description: public german tv channels
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  http: ^1.0.0
  m3u_nullsafe: ^1.0.4

dev_dependencies:
  lint: ^2.8.0